### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_module'

### ISSUE THREAD

**Issue by jwilk** [euske/pyntch#5]
```console
$ echo 'import argparse' > test.py
$ tchecker.py test.py
loading: 'test.py' as 'test'
 loading: '/usr/lib/python2.7/argparse.py' as 'argparse'
  loading: '/usr/lib/python2.7/collections.py' as 'collections'
   loading: '/usr/lib/python2.7/_abcoll.py' as '_abcoll'
    loading: '/usr/lib/python2.7/abc.py' as 'abc'
     loading: '/usr/lib/python2.7/_weakrefset.py' as '_weakrefset'
      not found: '_weakref'
Traceback (most recent call last):
  File "/home/jwilk/.local/bin/tchecker.py", line 98, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/home/jwilk/.local/bin/tchecker.py", line 68, in main
    modules.append(Interpreter.load_file(name, path, modpath))
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 308, in load_file
    module.set(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 171, in set
    build_stmt(self, self.frame, self.space, tree, [], isfuncdef=True)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 295, in build_stmt
    build_stmt(reporter, frame, space, tree.node, evals)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 351, in build_stmt
    exit = build_stmt(reporter, frame, space, stmt, evals, parent_space=parent_space)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 443, in build_stmt
    modules = tree._module.load_module(name)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 215, in load_module
    level=self.level+1)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 327, in load_module
    module = klass.load_file(modname or name, path, modpath, level=level)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 308, in load_file
    module.set(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 171, in set
    build_stmt(self, self.frame, self.space, tree, [], isfuncdef=True)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 295, in build_stmt
    build_stmt(reporter, frame, space, tree.node, evals)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 351, in build_stmt
    exit = build_stmt(reporter, frame, space, stmt, evals, parent_space=parent_space)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 443, in build_stmt
    modules = tree._module.load_module(name)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 215, in load_module
    level=self.level+1)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 327, in load_module
    module = klass.load_file(modname or name, path, modpath, level=level)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 308, in load_file
    module.set(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 170, in set
    self.space.register_names_top(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/namespace.py", line 362, in register_names_top
    self.register_names(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/namespace.py", line 99, in register_names
    self.register_names(tree.node)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/namespace.py", line 155, in register_names
    self.register_names(stmt)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/namespace.py", line 219, in register_names
    module = tree._module.load_module(modname)[-1]
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 215, in load_module
    level=self.level+1)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 327, in load_module
    module = klass.load_file(modname or name, path, modpath, level=level)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 308, in load_file
    module.set(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 171, in set
    build_stmt(self, self.frame, self.space, tree, [], isfuncdef=True)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 295, in build_stmt
    build_stmt(reporter, frame, space, tree.node, evals)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 351, in build_stmt
    exit = build_stmt(reporter, frame, space, stmt, evals, parent_space=parent_space)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 455, in build_stmt
    modules = tree._module.load_module(modname)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 215, in load_module
    level=self.level+1)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 327, in load_module
    module = klass.load_file(modname or name, path, modpath, level=level)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 308, in load_file
    module.set(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 171, in set
    build_stmt(self, self.frame, self.space, tree, [], isfuncdef=True)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 295, in build_stmt
    build_stmt(reporter, frame, space, tree.node, evals)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 351, in build_stmt
    exit = build_stmt(reporter, frame, space, stmt, evals, parent_space=parent_space)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 455, in build_stmt
    modules = tree._module.load_module(modname)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 215, in load_module
    level=self.level+1)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 327, in load_module
    module = klass.load_file(modname or name, path, modpath, level=level)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 308, in load_file
    module.set(tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/module.py", line 171, in set
    build_stmt(self, self.frame, self.space, tree, [], isfuncdef=True)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 295, in build_stmt
    build_stmt(reporter, frame, space, tree.node, evals)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 351, in build_stmt
    exit = build_stmt(reporter, frame, space, stmt, evals, parent_space=parent_space)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 314, in build_stmt
    klass = PythonClassType(reporter, frame, space, tree, name, bases, evals, tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/klass.py", line 198, in __init__
    build_stmt(self, parent_frame, self.space, tree.code, evals, parent_space=parent_space)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 351, in build_stmt
    exit = build_stmt(reporter, frame, space, stmt, evals, parent_space=parent_space)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/syntax.py", line 303, in build_stmt
    defaults, tree.varargs, tree.kwargs, tree)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/function.py", line 91, in __init__
    self.space.register_names(tree.code)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/namespace.py", line 155, in register_names
    self.register_names(stmt)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/namespace.py", line 149, in register_names
    self.register_names(tree.vars)
  File "/home/jwilk/.local/lib/python2.7/site-packages/pyntch/namespace.py", line 358, in register_names
    raise SyntaxError('unsupported syntax: %r (%s:%r)' % (tree, tree._module.get_path(), tree.lineno))
AttributeError: 'NoneType' object has no attribute '_module'
```

Tested with git master (8169b30cde5b77d97feddb39bf4d74ce00e39f2c).

**Comment by gst** [comment]
I'm getting the same exact error.

**Comment by AngusGLChen** [comment]
> I'm getting the same exact error.

Any ideas about how we can avoid the error?
